export class ForeignerCheckinCondition {
    nSearchUserIDMust: number; // (操作用户ID)
    sSearchUserNameMust: string; // (操作用户)
    sGuestDocNameLike: string; // 酒店入住旅客出示的证件姓名
    sDocNoLikeL: string; // 酒店入住客人出示的证件号码
    nDocType: number; // 证件类型
    nSex: number; // 依据酒店旅客入住表
    sBornDateStart: string; // 出生日期开始->依据酒店旅客入住表
    sBornDateEnd: string; // 出生日期结束->依据酒店旅客入住表
    sHotelNameLike: string; // 酒店名称
    nProvinceID: number; // 省份ID
    nCityID: number; // 城市ID
    nDistrictID: number; // 地区ID
    sRoomNo: string; // 酒店房号
    sCheckInDateTimeStart: string; // 入住时间(查询开始时间)
    sCheckInDateTimeEnd: string; // 入住时间(查询结束时间)
    sNationality: string; // 国籍
    sDepartureTimeStart: string; // 离境时间(查询的开始时间)
    sDepartureTimeEnd: string; // 离境时间(查询的结束时间)
    sEntryTimeStart: string; // 入境时间(查询的开始时间)
    sEntryTimeEnd: string; // 入境时间(查询的结束时间)
    sEntryPlace: string; // 入境地点
    sDeparturePlace: string; // 离境地点
    sVisaType: string; // 签证类型
    sVisaDeadline: string; // 签证失效时间
    lsMatchResult: number[]; // 认证类型
    nGuestState: number; // 住宿状态
}
